#define F (1 << 14)
#define convert_i_to_f(n) ((n) * (F))
#define convert_f_to_i_floor(x) ((x) / (F))
#define convert_f_to_i_nearest(x) ((x) >= 0 ? (((x) + (F) / 2) / (F)) : ((x) <= 0) ? (((x) - (F) / 2) / (F)) : (x))
#define add_f_and_f(x, y) ((x) + (y))
#define add_f_and_i(x, n) ((x) + (n) * (F))
#define sub_f_from_f(x, y) ((x) - (y))
#define sub_i_from_f(n, x) ((x) - (n) * (F))
#define mul_f_and_f(x, y) (((int64_t) (x)) * (y) / (F))
#define mul_f_and_i(x, n) ((x) * (n))
#define div_f_by_f(x, y) (((int64_t) (x)) * (F) / (y))
#define div_f_by_i(x, n) ((x) / (n))